name: Docker Image CI

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to the main branch

env:
  DOCKER_IMAGE: janvisen05/github-pipeline-run1 # Replace with your Docker Hub username and repository name

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Run on a fresh Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx for advanced features

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use a GitHub secret for Docker Hub username
          password: ${{ secrets.DOCKEN_TOKEN }} # Use a GitHub secret for Docker Hub token

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the current directory
          push: true # Push the image to Docker Hub
          tags: ${{ env.DOCKER_IMAGE }}:latest # Tag the image with "latest"
